services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    ports:
      - 5432:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  prisma:
    container_name: prisma
    build:
      context: .
      dockerfile: prisma/Dockerfile
    ports:
      - 5555:5555
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    working_dir: /schema
    volumes:
      - ../schema:/schema
    restart: always
    depends_on:
      - postgres
    command: ["bash", "local.sh"]
